language: generic

sudo: required

cache:
  directories:
    - darknet_ros/yolo_network_config/weights

services:
  - docker

env:
  global:
    secure: "Duif78VfiFbF1uuoxCs1oLIvP4K/sQj13y6C7d8taHvHUHsUDaKBHT4YjEDNw/WrD7E2nbqX4TNGm6XBZLjK+1pdEllYR5I27bQxxA7jSPOgWFVlXPPilkBp7CogHzAI04p/18jVGpRVfJ7P7PMbgLx1yl8nOSJk9wsxSU+++P4EsbOsVumVtR+ThUb5xYquBsACVcYsRxAMhC84+/oEhgA/u5UWedUmzG1VZ6e0M8iJ7t4kf0b+lBFG9V1SFFFCHBesEaEMI/OOA8GwROrJkNOXMOWILsdApfaIyLNN+wl9VP/7+SopU7Rhn0e+DVa0k8VcMDR2DVj4ExsH22kSjKN1fLvylPWZNZlnAJUIaciF86USF5Wni/0qWTl5D56PtHdwgR1r+g2OnwmuJiASXV90QlyVfhC2sClnC4EppRu0FZJU99lhAQDTKsTCll8mWVuZqZrOypkGUOKRGeGyLfe61vlb1EWdGzzXWqijS8JtLflCAeZ7skn8FeDBOdhs5Br0xVru9apWUe5kJuYNUpSNZqwCKMKL2D1sUhJegh3cvB0SxW8UF/IIsSo6tWPi+Bslqnj8At2dUtyo+ZAV7Zf5nT1chhgBXGtf2LLEJfxr9LLjCKJTRCcBdtojAKKNcN/Foq2rdf38LWx/HIy3XwGfc8CE8Zlspm958Vfj8yc="
  matrix:
    - TARGET=cpu COMPUTE=-1
    - TARGET=gpu COMPUTE=61
    - TARGET=gpu COMPUTE=52
    - TARGET=gpu COMPUTE=37

before_install:
  - echo "Branch is $TRAVIS_BRANCH"
  - sudo apt-get -qq update
  - sudo apt-get -q install -y python-pip wget
  - sudo pip -q install awscli

script:

  - set -e
  - bash build_image.sh ${TARGET} ${COMPUTE}

deploy:
  provider: script
  script: bash push_image.sh ${TARGET} ${COMPUTE}
  on:
    branch: master
