FROM nvidia/cuda:9.0-devel

ARG NVIDIA_COMPUTE=compute_52
ENV NVIDIA_COMPUTE=${NVIDIA_COMPUTE}

# Source the CUDA requirements
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-9.0/lib64
ENV PATH=${PATH}:/usr/local/cuda-9.0/bin

# Install ROS Kinetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list' \
    && apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
