subscribers:

  camera_reading:
    topic: /tut_image_to_classify
    queue_size: 1

actions:

  camera_reading:
    topic: /sut/check_for_objects

publishers:

  object_detector:
    topic: /sut/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /sut/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /sut/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  use_darknet: false
  wait_key_delay: 2
  enable_console_output: true
